# Generated by Django 5.0.4 on 2024-04-19 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('interest_areas', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('interest_areas', models.CharField(max_length=50)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('txtfile', models.FileField(blank=True, upload_to='text_files/')),
                ('text_conversation', models.TextField(blank=True, null=True)),
                ('txtjson', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
