# Generated by Django 5.0.4 on 2024-04-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPedidos', '0002_remove_form_user_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_user',
            old_name='txtfile',
            new_name='chat_file',
        ),
        migrations.RenameField(
            model_name='form_user',
            old_name='text_conversation',
            new_name='text_chat',
        ),
    ]
