# Generated by Django 5.0.4 on 2024-04-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPedidos', '0003_product'),
        ('AppPedidos', '0003_rename_txtfile_form_user_chat_file_and_more'),
    ]

    operations = [
    ]
