# Generated by Django 5.0.4 on 2024-04-20 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPedidos', '0004_merge_20240419_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chat_file', models.FileField(blank=True, upload_to='text_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='form_user',
            name='chat_file',
        ),
        migrations.RemoveField(
            model_name='form_user',
            name='text_chat',
        ),
        migrations.RemoveField(
            model_name='form_user',
            name='txtjson',
        ),
        migrations.AddField(
            model_name='client',
            name='text_chat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='txtjson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
